name: Deploy to IPFS

permissions:
  contents: write  # Changed to write to allow creating releases
  pull-requests: write
  statuses: write

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Next.js app
        run: pnpm build

      - name: Deploy to IPFS
        uses: aquiladev/ipfs-action@master
        id: ipfs
        with:
          path: ./out
          service: ipfs
          verbose: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            IPFS Hash: ${{ steps.ipfs.outputs.hash }}
            
            Gateway URLs:
            - https://ipfs.io/ipfs/${{ steps.ipfs.outputs.hash }}
            - https://cloudflare-ipfs.com/ipfs/${{ steps.ipfs.outputs.hash }}
            - https://gateway.ipfs.io/ipfs/${{ steps.ipfs.outputs.hash }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
